name: build xapian
on:
  workflow_dispatch:
    inputs:
      xapian_version:
        type: choice
        description: Xapian version
        default: 1.4.22
        options:
          - 1.4.22
          - 1.4.21
          - 1.4.20
          - 1.4.19
          - 1.4.18

jobs:
  xapian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: docker/Dockerfile.xapian
          tags: papermerge/many-linux-with-xapian:${{ inputs.xapian_version }}
          build-args: |
            XAPIAN_VERSION=${{inputs.xapian_version}}
